# Generated by Django 2.2 on 2024-04-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(default='images/none/default.jpg', upload_to='images')),
                ('address', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
