# Generated by Django 5.0.4 on 2024-04-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_review_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='address',
        ),
        migrations.AddField(
            model_name='review',
            name='short',
            field=models.CharField(default='A Juicy Game Review', max_length=200),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Reviews.review')),
            ],
        ),
    ]
