# Generated by Django 5.0.4 on 2024-04-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_remove_review_address_review_short_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(default='images/none/default.jpg', upload_to='game_images'),
        ),
    ]
