# Generated by Django 5.0.4 on 2024-04-26 02:18

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='steam_url',
            field=models.URLField(default='https://steamcommunity.com'),
        ),
        migrations.AlterField(
            model_name='review',
            name='url',
            field=embed_video.fields.EmbedVideoField(default='https://youtu.be/GhLMEFOBXqo?si=RemdII9VdRmQZ5UL'),
        ),
    ]
